In [23]:
import numpy as np
import pandas as pd
from pandas import Series

subjects = ['國文', '英文', '數學', '地理', '歷史']

def countFails(s:Series):
    failSubjects = s[s < 60]
    count = failSubjects.count()
    
    return count

def main():
    scores = np.random.randint(50, 101, size=(50, 5))
    scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))

    scores_sum = scores_df.sum(axis=1)
    scores_average = scores_df.mean(axis=1)

    scores_df['總分'] = scores_sum
    scores_df['平均'] = scores_average

    scores_df['不及格的科目數'] = scores_df[subjects].apply(countFails, axis=1)

    display(scores_df)

main()

    國文   英文   數學   地理   歷史   總分    平均  不及格的科目數
1   99   94   68   63   79  403  80.6        0
2   76  100  100   83   72  431  86.2        0
3   56   70   63   62   68  319  63.8        1
4   53   91   91   83   97  415  83.0        1
5   79   73   50   61   52  315  63.0        2
6   50   57   88   88   76  359  71.8        2
7   74   55   72   60   54  315  63.0        2
8   84   67   82   67   63  363  72.6        0
9   85   62   89   74   82  392  78.4        0
10  82   77   68   93   91  411  82.2        0
11  78   70   56   78   88  370  74.0        1
12  70   78   53   76   77  354  70.8        1
13  62   62   64   83   55  326  65.2        1
14  54   83   56   82   81  356  71.2        2
15  83   85   90   78   69  405  81.0        0
16  77  100   81   70   85  413  82.6        0
17  70   61   73   56   64  324  64.8        1
18  77   81   52   75   66  351  70.2        1
19  69   83   67   54   54  327  65.4        2
20  89   53   83   72   75  372  74.4        1
21  88   73   93   58   60  372  74.4        1
22  75   77   70   52   71  345  69.0        1
23  58   97   93   68   62  378  75.6        1
24  56   66   87   52   84  345  69.0        2
25  85   50   50   55  100  340  68.0        3
26  67   79   76   68   82  372  74.4        0
27  83   96   50   63   75  367  73.4        1
28  50   66   63   90   96  365  73.0        1
29  80   64   90   83   80  397  79.4        0
30  70   90   56   89   67  372  74.4        1
31  67   62   66   61   60  316  63.2        0
32  62   81   61  100   98  402  80.4        0
33  57   63   55   69   65  309  61.8        2
34  71   94   74   58   60  357  71.4        1
35  68   59   92   52   83  354  70.8        2
36  88   69   86   72   97  412  82.4        0
37  77   85   65   57   98  382  76.4        1
38  77   76   69   71   51  344  68.8        1
39  65   59  100   59   98  381  76.2        2
40  97   57   67   51   59  331  66.2        3
41  53   70   60   59   74  316  63.2        2
42  90  100   92   62   84  428  85.6        0
43  57   66   80   85   93  381  76.2        1
44  95   55   58   96   50  354  70.8        3
45  82   78   82   77   70  389  77.8        0
46  50   77   92   96   95  410  82.0        1
47  74   98   57   74   83  386  77.2        1
48  54   71   71  100   83  379  75.8        1
49  88   96   93   80   51  408  81.6        1
50  63   50   93   56   85  347  69.4        2

In [12]:
import pandas as pd

df1 = pd.read_csv('各鄉鎮市區人口密度.csv')
df1.columns = df1.iloc[0]
df2 = df1.drop(index=0)
df3 = df2.dropna()
df4 = df3.drop(index=[369, 370])
df5 = df4.set_index(['區域別'])
df6 = df5.drop(columns=['統計年'])
df6['年底人口數'] = pd.to_numeric(df6['年底人口數'], downcast='integer')
df6['土地面積'] = pd.to_numeric(df6['土地面積'], downcast='float')
df6['人口密度'] = pd.to_numeric(df6['人口密度'], downcast='integer')

df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 368 entries, 新北市板橋區 to 連江縣東引鄉
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   368 non-null    int32
 1   土地面積    368 non-null    float32
 2   人口密度    368 non-null    int32
dtypes: float32(1), int32(2)
memory usage: 7.2+ KB