In [4]:
import numpy as np
import pandas as pd

subjects = ['國文', '英文', '數學', '地理', '歷史']

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))

scores_sum = scores_df.sum(axis=1)
scores_average = scores_df.mean(axis=1)

scores_df

     國文  英文   數學   地理  歷史
1    61  51   87   86  98
2    69  90   98   58  94
3    72  67   85   72  86
4    93  73   62   56  57
5    79  86   89   88  62
6    72  51   92   57  54
7    85  96   71   98  78
8    54  76  100   88  54
9    58  81   72   88  80
10   59  90   86   64  64
11   94  94   51   80  53
12   62  85   72   57  95
13   84  66   65   66  69
14   82  97   50   93  76
15   98  78   71   86  85
16   63  81   99   73  78
17   71  92   51   53  84
18   57  92   96   81  50
19   81  80  100   88  93
20   68  51   86   78  73
21   98  90   73   69  74
22   72  65   51   89  60
23   56  68   93   76  98
24   53  96   92   58  95
25   69  85   71  100  81
26   66  97   69   69  58
27   77  63   68   96  76
28   56  85   75   79  88
29   54  88   89   73  77
30   68  90   80   95  94
31   66  66   66   61  93
32   80  76   57   84  91
33   90  60   55   76  94
34   75  61   94   83  96
35   78  73   50   56  82
36   70  68   71   87  61
37   69  89   81   50  83
38   55  74   57   84  64
39   86  59   88   69  53
40   69  63   74   54  98
41   87  59   76   80  59
42   97  93   66   52  58
43   66  51   77   59  84
44   53  88   59   53  60
45   62  65   97   72  90
46   53  65   71   97  77
47   77  90   88   88  50
48   69  80   58   75  57
49   84  76   98   59  76
50  100  75   86   78  90

In [5]:
from pandas import Series

def to_ststistic(value:Series) -> Series:
    return Series([value.max(), value.min(), value.mean()], index=['最高分', '最低分', '平均分'])

scores_df.apply(to_ststistic)

         國文    英文      數學      地理    歷史
最高分  100.00  97.0  100.00  100.00  98.0
最低分   53.00  51.0   50.00   50.00  50.0
平均分   72.34  76.7   76.26   74.62  76.0